### ISSUE TITLE
use caching for db.order

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#12]
db.order is used in 2 places here when useArray equals `true`
https://github.com/robtweed/ewd-document-store/blob/a771f87d7d6e09bf28719b3be8cd139054dd9c0f/lib/proto/getDocument.js#L57
https://github.com/robtweed/ewd-document-store/blob/a771f87d7d6e09bf28719b3be8cd139054dd9c0f/lib/proto/getDocument.js#L87

I think cache pattern may be used here...

**Comment by robtweed** [comment]
Could you explain what you're getting at please?

**Comment by killmenot** [comment]
I noted that if `useArray` is `true` then `db.order` called almost 2 times often. The reason of it is that before documentNode is processed for sub nodes, we need to determine `isArray` or not and call `arrayOfSubscripts` function. It process node and does calls if node stores array.
https://github.com/robtweed/ewd-document-store/blob/a771f87d7d6e09bf28719b3be8cd139054dd9c0f/lib/proto/getDocument.js#L57
The same calls repeated later here: https://github.com/robtweed/ewd-document-store/blob/a771f87d7d6e09bf28719b3be8cd139054dd9c0f/lib/proto/getDocument.js#L90

The goal is to implement some functionality that caches db.order request for arrays. This may increase the performance for large objects. However, you can ignore it. I do not think it's necessary change

**Comment by robtweed** [comment]
Right - so this is the logic where it's first testing that a set of subscripts in a global (at a particular level of subscripting) can be mapped to an array, because it's a consecutive unbroken sequence of numeric values starting at 0 (or 1, depending on the offset).  Yes - I should probably cache the values during the test to save another pass if it does prove to be an array.  If it doesn't prove to be an array, then for now I'll discard the cache and let it do a re-run, treating the subscripts as members of an object instead

**Comment by robtweed** [comment]
Actually looking at this again, I'm not sure the savings are worth it - in order to cache the values on the 1st exploratory pass, I'd have to not only do a db.order(), I'd have to check defined to see what kind of a node it is, and then do a db.get() if it's a leaf node.  Given that I've already provided warnings in the tutorials about the potential cost of useArrays = true if an in-global array is huge (which it could be), people should only be using it where arrays are pretty small, in which case it's not a big overhead to repeat the logic.  I think we'd be substituting what's currently clean logic with more complex (and therefore potentially brittle) logic just to occasionally save a bit of time

**Comment by killmenot** [comment]
Agreed
