### ISSUE TITLE
what is the purpose of `seed`variable?

### ISSUE THREAD

**Issue by killmenot** [robtweed/ewd-document-store#4]
https://github.com/robtweed/ewd-document-store/blob/55179cb34490bb63f8d086d93d40b647c98cc960/lib/proto/forEach.js#L101

**Comment by robtweed** [comment]
Whilst the seed variable itself isn't needed, that db.previous(node).result is needed, in order to reset the starting point of the order loop back one "step", so the first value that emerges is the one specified in the "from" value.  In that sense seed doesn't do any harm, so I'd prefer to leave it there
